# This file was generated by GoReleaser. DO NOT EDIT.
cask "go42x" do
  version "0.34.0"

  on_macos do
    on_arm do
      sha256 "51b3b1553d65c50f62626030654857ff54c9a9c8037a9450f526e68c8fb9ebef"
      url "https://github.com/go42-dev/go42x/releases/download/v#{version}/go42x_#{version}_macOS_arm64.tar.gz"
    end
    on_intel do
      sha256 "3ae231318f294deba0fd0cbb9a69edd2e8ead57a05706087dbc486047c3ced96"
      url "https://github.com/go42-dev/go42x/releases/download/v#{version}/go42x_#{version}_macOS_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "121e0a58dee728d8b20dc550582369a6c380de086c3b59a70f002b05087b38a2"
      url "https://github.com/go42-dev/go42x/releases/download/v#{version}/go42x_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "89fe097b492458895a5abe55f23dbc47efc6e3706ec6097a51e37935f9738104"
      url "https://github.com/go42-dev/go42x/releases/download/v#{version}/go42x_#{version}_linux_x86_64.tar.gz"
    end
  end

  name "go42x"
  desc "Helper tool for go42 project"
  homepage "https://github.com/go42-dev/go42x"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go42x"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/go42x"]
    end
  end

  # No zap stanza required
end
