# This file was generated by GoReleaser. DO NOT EDIT.
cask "go42x" do
  version "0.30.0"

  on_macos do
    on_arm do
      sha256 "c01e64a0baca110f3a73a8c8edb62a9d57555db5de00b68c38020943537b2cf2"
      url "https://github.com/go42-dev/go42x/releases/download/v#{version}/go42x_#{version}_macOS_arm64.tar.gz"
    end
    on_intel do
      sha256 "384e1b87960ce6a920997dff2bccdf99a729fef884fd796703f1fde067d788e6"
      url "https://github.com/go42-dev/go42x/releases/download/v#{version}/go42x_#{version}_macOS_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7ec6d627ad8d768c27231d2dac569cab8d27ea91b43b2c668d057df2f2931c80"
      url "https://github.com/go42-dev/go42x/releases/download/v#{version}/go42x_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a9d4680d9e472a78639e2b7f887f9ed7959cf66540bf66024bdb4aed3dc226c0"
      url "https://github.com/go42-dev/go42x/releases/download/v#{version}/go42x_#{version}_linux_x86_64.tar.gz"
    end
  end

  name "go42x"
  desc "Helper tool for go42 project"
  homepage "https://github.com/go42-dev/go42x"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go42x"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/go42x"]
    end
  end

  # No zap stanza required
end
