# This file was generated by GoReleaser. DO NOT EDIT.
cask "go42x" do
  version "0.31.0"

  on_macos do
    on_arm do
      sha256 "ceb9308bbf08f58bd62bfb53eea3c93cc071d81ff6e9c2fdc6ecff68503cad58"
      url "https://github.com/go42-dev/go42x/releases/download/v#{version}/go42x_#{version}_macOS_arm64.tar.gz"
    end
    on_intel do
      sha256 "9ffc8870cb9dc4ad9851330c86e25fb01cbac6fa3fa146241b7096e8400f690a"
      url "https://github.com/go42-dev/go42x/releases/download/v#{version}/go42x_#{version}_macOS_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f089d11525d3f0c9fc70fb5b955989cf750eff70c0651463f2343d1e60290afe"
      url "https://github.com/go42-dev/go42x/releases/download/v#{version}/go42x_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "722b9eeb2f09602e7dcd38a4e3346b2d534406282bd71962031323a2da2f0ca9"
      url "https://github.com/go42-dev/go42x/releases/download/v#{version}/go42x_#{version}_linux_x86_64.tar.gz"
    end
  end

  name "go42x"
  desc "Helper tool for go42 project"
  homepage "https://github.com/go42-dev/go42x"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go42x"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/go42x"]
    end
  end

  # No zap stanza required
end
